pub mod app_view;
pub mod approval_prompt_bar;
pub use chatty_core::models::attachment_validation;
mod chart_renderer;
pub mod chat_input;
pub mod chat_view;
pub mod code_block_component;
pub mod conversation_item;
pub mod diff_view_component;
pub mod error_log_dialog;
pub mod footer;
pub mod math_parser;
pub mod math_renderer;
pub mod mermaid_component;
pub mod message_component;
pub use chatty_core::models::message_types;
pub mod parsed_cache;
pub mod sidebar_view;
pub mod syntax_highlighter;
pub mod titlebar;
pub mod trace_components;

pub use chat_view::ChatView;
pub use error_log_dialog::ErrorLogDialog;
pub use sidebar_view::SidebarView;
pub use titlebar::AppTitleBar;
