//! Fixture `padded`: behaves exactly like `echo-agent`'s `chat`, but the
//! compiled `.wasm` is padded to roughly 5 MiB with a non-zero, non-uniform
//! data segment, so wasm-opt/LLVM cannot fold it into a cheap `memory.fill`
//! and the loader actually reads and validates the extra bytes. Used only to
//! measure cold-load time of a large module (AGE-603 / S7).
use chatty_module_sdk::{export_module, ToolDefinition};
use chatty_module_sdk::{AgentCard, ChatRequest, ChatResponse, ModuleExports, Role};

// Generated by build.rs: a ~5 MiB non-uniform, non-zero blob so the wasm
// data segment can't be folded into a cheap `memory.fill`.
static PAD: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/pad.bin"));

fn last_user(req: &ChatRequest) -> &str {
    let user = req.messages.iter().rfind(|m| m.role == Role::User);
    user.map_or("", |m| m.content.as_str())
}

#[derive(Default)]
struct Fixture;

impl ModuleExports for Fixture {
    fn chat(&self, req: ChatRequest) -> Result<ChatResponse, String> {
        // Touch PAD so the linker can't drop it, without doing real work.
        let checksum = *std::hint::black_box(PAD).first().unwrap_or(&0);
        let content = format!("Echo: {} (pad={checksum})", last_user(&req));
        Ok(ChatResponse {
            content,
            tool_calls: vec![],
            usage: None,
        })
    }

    fn invoke_tool(&self, name: String, _args: String) -> Result<String, String> {
        Err(format!("unknown tool: {name}"))
    }

    fn list_tools(&self) -> Vec<ToolDefinition> {
        vec![]
    }

    fn get_agent_card(&self) -> AgentCard {
        AgentCard {
            name: "padded".to_string(),
            display_name: "Padded".to_string(),
            description: "Test fixture with a ~5 MiB binary.".to_string(),
            version: "0.1.0".to_string(),
            skills: vec![],
            tools: vec![],
        }
    }
}

export_module!(Fixture);
