#!/usr/bin/env bash
# AGE-302 / ADR-0011 — A/A between `sub_agent` and `invoke_agent` over the
# broker. One fixed delegated task, N runs per arm, same host, same model,
# no VM.
#
#   scripts/broker-ab-measurement.sh [output.md]
#
# Environment:
#   RUNS=10                      runs per arm
#   OLLAMA_URL=http://localhost:11434
#   OLLAMA_MODEL=qwen2.5:0.5b    the model both arms use
#   TASK="..."                   the delegated task
#   PROFILE=release              cargo profile (release is what ships)
#
# The run gets its own XDG_CONFIG_HOME, so it cannot read or write a real
# chatty configuration — no API keys are in scope and no conversation
# database is touched. Both arms spawn `chatty-tui` by name, so the built
# binary is put on PATH rather than installed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

RUNS="${RUNS:-10}"
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"
OLLAMA_MODEL="${OLLAMA_MODEL:-qwen2.5:0.5b}"
PROFILE="${PROFILE:-release}"
MODEL_ID="ollama-measurement"
OUT="${1:-docs/research/adr-0011-broker-ab-$(date +%Y-%m-%d).md}"

# ── An isolated configuration ────────────────────────────────────────────────
WORK="$(mktemp -d /tmp/age302.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
export XDG_CONFIG_HOME="$WORK/config"
export XDG_DATA_HOME="$WORK/data"
CHATTY_CONFIG="$XDG_CONFIG_HOME/chatty"
mkdir -p "$CHATTY_CONFIG" "$XDG_DATA_HOME"

cat > "$CHATTY_CONFIG/providers.json" <<JSON
[
  {
    "name": "Ollama (measurement)",
    "provider_type": "ollama",
    "base_url": "$OLLAMA_URL"
  }
]
JSON

cat > "$CHATTY_CONFIG/models.json" <<JSON
[
  {
    "id": "$MODEL_ID",
    "name": "Ollama measurement model",
    "provider_type": "ollama",
    "model_identifier": "$OLLAMA_MODEL",
    "temperature": 0.0,
    "preamble": "",
    "supports_images": false,
    "supports_pdf": false,
    "supports_temperature": true,
    "max_context_window": 32768,
    "source": "user",
    "is_favorite": false,
    "is_default": true
  }
]
JSON

# Tools on, approvals off: a worker that stops to ask cannot be timed, and
# both arms get the identical policy.
# `timeout_seconds`, `max_output_bytes` and `network_isolation` carry no serde
# default: omitting them makes the whole file fail to parse, the settings fall
# back to defaults, and the worker silently gets no tools at all.
cat > "$CHATTY_CONFIG/execution_settings.json" <<JSON
{
  "enabled": true,
  "approval_mode": "auto_approve_all",
  "workspace_dir": "$WORK/workspace",
  "filesystem_read_enabled": true,
  "filesystem_write_enabled": true,
  "fetch_enabled": false,
  "git_enabled": false,
  "browser_enabled": false,
  "execute_code_enabled": false,
  "docker_code_execution_enabled": false,
  "timeout_seconds": 60,
  "max_output_bytes": 51200,
  "network_isolation": false,
  "max_agent_turns": 6,
  "memory_enabled": false,
  "embedding_enabled": false
}
JSON
mkdir -p "$WORK/workspace"
# The delegated task needs a tool call to be worth diffing, and one whose
# result is deterministic. Reading a known file is both.
printf 'platypus\n' > "$WORK/workspace/task.txt"

# ── Preconditions ────────────────────────────────────────────────────────────
if ! curl -sf --max-time 5 "$OLLAMA_URL/api/tags" > /dev/null; then
  echo "error: no Ollama at $OLLAMA_URL. Start it with: ollama serve" >&2
  exit 1
fi
if ! curl -sf --max-time 5 "$OLLAMA_URL/api/tags" | grep -q "\"$OLLAMA_MODEL\""; then
  echo "error: $OLLAMA_MODEL is not pulled. Run: ollama pull $OLLAMA_MODEL" >&2
  exit 1
fi

# ── Build ────────────────────────────────────────────────────────────────────
BUILD_FLAG=""
[[ "$PROFILE" == "release" ]] && BUILD_FLAG="--release"
echo "building chatty-tui and the harness ($PROFILE) …" >&2
cargo build $BUILD_FLAG -p chatty-tui
cargo build $BUILD_FLAG -p chatty-tui --example broker_ab

BIN_DIR="$REPO_ROOT/target/$PROFILE"
export PATH="$BIN_DIR:$PATH"
command -v chatty-tui > /dev/null || { echo "error: chatty-tui not on PATH" >&2; exit 1; }

# ── Host facts, so the numbers mean something later ──────────────────────────
mkdir -p "$(dirname "$OUT")"
{
  echo "# ADR-0011 kill criteria — \`sub_agent\` vs the broker (AGE-302)"
  echo
  echo "Generated by \`scripts/broker-ab-measurement.sh\` on $(date -Iseconds)."
  echo
  echo "## Setup"
  echo
  echo "| | |"
  echo "|---|---|"
  echo "| Host | $(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | xargs), $(nproc) threads, $(free -g | awk '/^Mem:/{print $2}') GiB |"
  echo "| Kernel | $(uname -sr) |"
  echo "| Build | \`$PROFILE\`, $(git rev-parse --short HEAD) |"
  echo "| Model | \`$OLLAMA_MODEL\` via Ollama at \`$OLLAMA_URL\` (same model both arms) |"
  echo "| Runs | $RUNS per arm, interleaved, after one warm-up per arm |"
  echo "| Isolation | neither arm gets a \`git worktree\`; the criterion is about the hop |"
  echo "| VM | none, as the issue specifies |"
  echo
} > "$OUT"

echo "measuring …" >&2
# From the workspace: the filesystem tools resolve relative paths against the
# process's directory, and both arms' children inherit this one, so neither is
# advantaged by where the harness happened to be started.
OUT_ABS="$(cd "$(dirname "$OUT")" && pwd)/$(basename "$OUT")"
cd "$WORK/workspace"
RUNS="$RUNS" MODEL="$MODEL_ID" \
  TASK="${TASK:-Read the file task.txt and reply with the single word it contains.}" \
  SOCKET="$WORK/participants.sock" \
  "$BIN_DIR/examples/broker_ab" >> "$OUT_ABS"
cd "$REPO_ROOT"

echo "wrote $OUT" >&2
